/* Generated by Yosys 0.39 (git sha1 00338082b00, clang++ 15.0.0 -fPIC -Os) */

(* src = "/var/folders/w0/c22bkxtx7rxbztkhwvxhgpsm0000gn/T/ipykernel_42370/508760003.py:8" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module swapiq(dout, din);
  (* src = "/var/folders/w0/c22bkxtx7rxbztkhwvxhgpsm0000gn/T/ipykernel_42370/508760003.py:4" *)
  input [511:0] din;
  wire [511:0] din;
  (* src = "/var/folders/w0/c22bkxtx7rxbztkhwvxhgpsm0000gn/T/ipykernel_42370/508760003.py:5" *)
  output [511:0] dout;
  wire [511:0] dout;
  assign dout[511:496] = din[495:480];
  assign dout[495:480] = din[511:496];
  assign dout[479:464] = din[463:448];
  assign dout[463:448] = din[479:464];
  assign dout[447:432] = din[431:416];
  assign dout[431:416] = din[447:432];
  assign dout[415:400] = din[399:384];
  assign dout[399:384] = din[415:400];
  assign dout[383:368] = din[367:352];
  assign dout[367:352] = din[383:368];
  assign dout[351:336] = din[335:320];
  assign dout[335:320] = din[351:336];
  assign dout[319:304] = din[303:288];
  assign dout[303:288] = din[319:304];
  assign dout[287:272] = din[271:256];
  assign dout[271:256] = din[287:272];
  assign dout[255:240] = din[239:224];
  assign dout[239:224] = din[255:240];
  assign dout[223:208] = din[207:192];
  assign dout[207:192] = din[223:208];
  assign dout[191:176] = din[175:160];
  assign dout[175:160] = din[191:176];
  assign dout[159:144] = din[143:128];
  assign dout[143:128] = din[159:144];
  assign dout[127:112] = din[111:96];
  assign dout[111:96] = din[127:112];
  assign dout[95:80] = din[79:64];
  assign dout[79:64] = din[95:80];
  assign dout[63:48] = din[47:32];
  assign dout[47:32] = din[63:48];
  assign dout[31:16] = din[15:0];
  assign dout[15:0] = din[31:16];
endmodule
