[project]
name = "mkidaranth"
version = "0.1.0"
description = "amaranth blocks for MKID Readout"
authors = [
    {name = "Aled Cuda", email = "aled@ucsb.edu"},
]
dependencies = [
    "amaranth>=0.5.8",
    "amaranth-soc @ git+https://github.com/amaranth-lang/amaranth-soc",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "GPL"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.scripts]
test.composite = ["test-code"]
test-code.cmd = "python -m coverage run -m unittest discover -t . -s tests -v"


[dependency-groups]
dev = [
    "amaranth-yosys>=0.50.0",
    "coverage>=7.6.1",
    "ipython>=8.29.0",
    "ipykernel>=6.30.1",
    "jupyterlab>=4.4.5",
]
